version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "7218:80"  
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Database=blogDB;Username=postgres;Password=1111
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: blogDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
